// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfWWwOvEMULFtz-F9EioMZ0QhEZo0y7iU',
    appId: '1:989372558032:web:24610ea0a7d4debbb68cd5',
    messagingSenderId: '989372558032',
    projectId: 'myfirebasefirst-a6ed4',
    authDomain: 'myfirebasefirst-a6ed4.firebaseapp.com',
    storageBucket: 'myfirebasefirst-a6ed4.firebasestorage.app',
    measurementId: 'G-714WPMPEEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiaDw4URHOqAZZs0odqxsnGBI4oxmHum4',
    appId: '1:989372558032:android:7d7c6ddfefb18eb7b68cd5',
    messagingSenderId: '989372558032',
    projectId: 'myfirebasefirst-a6ed4',
    storageBucket: 'myfirebasefirst-a6ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCozCMyCyc0uLQiuA8x2UYlEEMbHkySqi8',
    appId: '1:989372558032:ios:1fc5eca3df7b3711b68cd5',
    messagingSenderId: '989372558032',
    projectId: 'myfirebasefirst-a6ed4',
    storageBucket: 'myfirebasefirst-a6ed4.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuthLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCozCMyCyc0uLQiuA8x2UYlEEMbHkySqi8',
    appId: '1:989372558032:ios:1fc5eca3df7b3711b68cd5',
    messagingSenderId: '989372558032',
    projectId: 'myfirebasefirst-a6ed4',
    storageBucket: 'myfirebasefirst-a6ed4.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuthLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfWWwOvEMULFtz-F9EioMZ0QhEZo0y7iU',
    appId: '1:989372558032:web:3b1598dd950604fbb68cd5',
    messagingSenderId: '989372558032',
    projectId: 'myfirebasefirst-a6ed4',
    authDomain: 'myfirebasefirst-a6ed4.firebaseapp.com',
    storageBucket: 'myfirebasefirst-a6ed4.firebasestorage.app',
    measurementId: 'G-CXPP209T4Q',
  );

}